# Generated by Django 2.2 on 2022-01-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(verbose_name='date_create'),
        ),
    ]
