# Generated by Django 2.2 on 2022-01-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Condition',
        ),
    ]
