# Generated by Django 2.2 on 2022-01-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='condition',
        ),
    ]
